name: CheckValue

on: 
  workflow_dispatch:
    inputs:
      value:         
        description: 'value'
        type: boolean
        default: false

jobs:
  checkValue:
    name: check value
    runs-on: ubuntu-latest

    steps:
      - name: always truthy step
        if: true
        run: |
          echo foobar

      - name: alway falsy step
        if: false
        run: |
          echo foobar

      - if: ${{ github.event.inputs.value }}
        run: |
          echo input is truthy

      - if: ${{ ! github.event.inputs.value }}
        run: |
          echo input is falsy
