name: Release

on: workflow_dispatch

jobs:
  assignVersion:
    name: assign version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          LAST_COMMIT=$(git rev-parse --short HEAD)
          echo $LAST_COMMIT

  deployDE:
    name: deploy de
    runs-on: ubuntu-latest
    needs: assignVersion

    steps:
      - run: |
          echo "deploying DE ($LAST_COMMIT)"

  deployAT:
    name: deploy at
    runs-on: ubuntu-latest
    needs: assignVersion

    steps:
      - run: |
          echo "deploying AT ($LAST_COMMIT)"
