name: Release

on: workflow_dispatch

jobs:
  assignVersion:
    name: assign version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          LAST_COMMIT=$(git rev-parse --short HEAD)
          echo $LAST_COMMIT

  deployDE:
    name: deploy de
    runs-on: ubuntu-latest
    needs: assignVersion
    environment: Production-DE

    steps:
      - uses: ./.github/actions/build
        with:
          BUILD_ID: DE

  deployAT:
    name: deploy at
    runs-on: ubuntu-latest
    needs: assignVersion
    environment: Production-AT

    steps:
      - uses: ./.github/actions/build
        with:
          BUILD_ID: AT

