name: Release

on: 
  workflow_dispatch:
    inputs:
      dryRun:         
        description: 'dryRun'     
        required: false
        default: 'false'

jobs:
  assignVersion:
    name: assign version
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo workflow input dryRun: ${{ github.event.inputs.dryRun }}

      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          LAST_COMMIT=$(git rev-parse --short HEAD)
          echo $LAST_COMMIT

  deployDE:
    name: deploy de
    runs-on: ubuntu-latest
    needs: assignVersion
    environment: Production-DE

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          BUILD_ID: DE
          API_SECRET: ${{ secrets.API_SECRET }}
          DRY_RUN: ${{ github.event.inputs.dryRun }}

  deployAT:
    name: deploy at
    runs-on: ubuntu-latest
    needs: assignVersion
    environment: Production-AT

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          BUILD_ID: AT
          API_SECRET: ${{ secrets.API_SECRET }}
          DRY_RUN: ${{ github.event.inputs.dryRun }}

