name: Release

on: workflow_dispatch

jobs:
  assignVersion:
    name: assign version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          LAST_COMMIT=$(git rev-parse --short HEAD)
          echo $LAST_COMMIT

  deployDE:
    name: deploy de
    runs-on: ubuntu-latest
    needs: assignVersion
    environment: Production-DE

    steps:
      - run: |
          touch build.de.tar.gz
          echo "VERSION DE" >> build.de.tar.gz
          echo "API_SECRET=${{secrets.API_SECRET}}" >> build.de.tar.gz
          ls -la

      - uses: actions/upload-artifact@v3
        with:
          name: build.de.tar.gz
          path: ./build.de.tar.gz

  deployAT:
    name: deploy at
    runs-on: ubuntu-latest
    needs: assignVersion
    environment: Production-AT

    steps:
      - run: |
          touch build.at.tar.gz
          echo "VERSION AT" >> build.at.tar.gz
          echo "API_SECRET=${{secrets.API_SECRET}}" >> build.at.tar.gz
          ls -la

      - uses: actions/upload-artifact@v3
        with:
          name: build.at.tar.gz
          path: ./build.at.tar.gz
